<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Facebook\Module'                        => __DIR__ . '/Module.php',
    'Facebook\Controller\FacebookController' => __DIR__ . '/src/Facebook/Controller/FacebookController.php',
    'FacebookTest\Framework\TestCase'        => __DIR__ . '/tests/Facebook/Framework/TestCase.php',
    'FacebookTest\SampleTest'                => __DIR__ . '/tests/Facebook/SampleTest.php',
);
